### ISSUE TITLE
Changes needed 

### ISSUE THREAD

**Issue by r-rishit27** [AICLUB-IIITDM/LearnML#2]
Add some mathematical topic intialy for machine learing which are prequistes like stats,probality,calclus etc.
Add hypothesis testing A/B TESTING ,GRADIENT DESCENT & COST FUNCTION,DIFFRENT TYPES OF ERRORS,VARIENCE AND BIAS ALONG WITH Z SCORE AND NORMALIZATION
REGARDS RISHIT

**Comment by chanakyavasantha** [comment]
Create a Pull request, ill merge
